name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
#  lint:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v4
#
#      - name: Lint
#        uses: cpp-linter/cpp-linter-action@v2.13.4
#        id: linter
#        with:
#          style: 'file'
#          tidy-checks: ''
#
#      - name: Check
#        if: steps.linter.outputs.checks-failed > 0
#        run: exit 1

  build-and-test:
    name: Build and Test (${{ matrix.os }} / ${{ matrix.build_type }})

    strategy:
      matrix:
        os: [ ubuntu-latest ]
        build_type: [ Debug ]

    runs-on: ${{ matrix.os }}

    env:
      BUILD_DIR: ${{ github.workspace }}/build

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Build Directory
        uses: actions/cache@v4
        with:
          path: ${{ env.BUILD_DIR }}
          key: ${{ runner.os }}-${{ matrix.build_type }}-${{ hashFiles('**/CMakeLists.txt') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.build_type }}-

      - name: Configure CMake
        run: cmake -B ${{ env.BUILD_DIR }} -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -S ${{ github.workspace }}

      - name: Build
        run: cmake --build ${{ env.BUILD_DIR }} --config ${{ matrix.build_type }}

      - name: Test
        working-directory: ${{ env.BUILD_DIR }}
        run: ctest -C ${{ matrix.build_type }} --output-on-failure