name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lint
        uses: cpp-linter/cpp-linter-action@v2
        id: linter
        with:
          style: 'file'
          tidy-checks: ''

      - name: Check
        if: steps.linter.outputs.checks-failed > 0
        run: exit 1

  build:
    runs-on: ubuntu-latest
    env:
      BUILD_TYPE: Release
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}